services:
  - type: web
    name: lks-siswa
    env: static
    plan: free
    branch: main
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
